### ISSUE TITLE
key meanings

### ISSUE THREAD

**Issue by rornor** [mediawiki-utilities/python-mwviews#6]
For single article_view I get dict with items like this:

```python
datetime.datetime(2016, 10, 23, 0, 0): {
	'D': 1066,
	'N': 942,
	'_': None,
	'a': 6,
	'e': 2,
	'i': 7,
	'l': 8,
	'm': 24,
	'n': 8,
	'o': 1,
	'p': 9,
	't': 8,
	'y': 4
}
```

What is the meaning of these keys?

Instantiating `PageviewsClient(parallelism=1)` gives same result.

**Comment by rornor** [comment]
Nevermind, rest service is simple, and there is no need for me to use a wrapper...

**Comment by milimetric** [comment]
@rornor You just passed a string instead of a list of strings as the second parameter.  It's supposed to be "articles" not "article" so instead of:

    p.article_views('en.wikipedia', 'Selfie')

You should've done:

    p.article_views('en.wikipedia', ['Selfie'])

That is somewhat confusing, so I'll add some logic to assume a single string is meant as a list with that string in it instead.
